# vim: set ts=2 sw=2 sts=2 et :

version: '3.3'

services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./test/fixtures/grafana_provisioning/:/etc/grafana/provisioning/
    depends_on:
      - slack

  workhorse:
    image: workhorse
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - grafana

  slack:
    image: ealen/echo-server:latest
