# vim: set ts=2 sw=2 sts=2 et :

version: '3.8'

services:
  grafana:
    image: grafana/grafana

  grafana_dashboard_generator:
    image: grafana-dashboard-generator
    build:
      context: .
      dockerfile: Dockerfile.python

  grafana_terraform_module:
    image: grafana-terraform-module
    build:
      context: .
      dockerfile: Dockerfile.terraform
