# vim: set ts=2 sw=2 sts=2 et :

version: '3.8'

services:
  grafana:
    environment:
      GF_SERVER_ROOT_URL: 'http://localhost:3000'
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
      GF_AUTH_DISABLE_LOGIN_FORM: 'false'
      GF_AUTH_BASIC_ENABLED: 'true'
      GF_LOG_LEVEL: 'info'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    volumes:
      - .:/opt/ct
    ports:
      - 3000:3000

  workhorse:
    volumes:
      - .:/opt/ct
    working_dir: /opt/ct
    depends_on:
      - grafana
